x-logging:
  &json-logging
  driver: json-file
  options:
    max-size: "1m"
    max-file: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        # architecture: amd64, arm32v5, arm64v8, i386, and so on.
        - ARCHITECTURE=arm64v8
        - UID=1000
        - GID=1003
        - USERNAME=user
    image: rag-backend
    container_name: rag-backend
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./env_files/backend/docker.env
      - ./env_files/backend/.env
      - ./env_files/database/.env
    networks:
      - rag-app
    volumes:
      - ./static:/static:ro
      - ./backend/app:/opt/app
      - ./backend/pyproject.toml:/opt/pyproject.toml
      - ./backend/bashrc:/opt/home/.bashrc:ro
      - storage:/data
    ports:
      - 7654:8000
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    command:
      - --reload
    restart: always
    logging: *json-logging

  celery:
    image: rag-backend
    container_name: rag-celery
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./env_files/backend/docker.env
      - ./env_files/backend/.env
      - ./env_files/database/.env
    networks:
      - rag-app
    working_dir: /opt
    volumes:
      - ./celery/entrypoint.sh:/opt/entrypoint.sh:ro
      - ./backend/app:/opt/app:ro
      - ./backend/bashrc:/opt/home/.bashrc:ro
      - storage:/data:ro
    depends_on:
      redis:
        condition: service_started
      backend:
        condition: service_started
    entrypoint: /opt/entrypoint.sh
    restart: always
    logging: *json-logging

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        # architecture: amd64, arm32v5, arm64v8, i386, and so on.
        - ARCHITECTURE=arm64v8
    image: rag-redis
    container_name: rag-redis
    networks:
      - rag-app
    volumes:
      - ./redis/redis.conf://usr/local/etc/redis/redis.conf:ro
    expose:
      - 6379
    restart: always
    logging: *json-logging

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        # architecture: amd64, arm32v5, arm64v8, i386, and so on.
        - ARCHITECTURE=arm64v8
        - PGVECTOR_VERSION=0.7.0
    image: rag-database
    container_name: rag-database
    env_file:
      - ./env_files/database/.env
    networks:
      - rag-app
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d:ro
      - database:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
    logging: *json-logging

networks:
  rag-app:
    name: rag-app
volumes:
  database:
    name: rag-database
  storage:
    name: rag-storage