# Generated by Django 4.2.11 on 2024-04-28 11:43

import chatbot.models.agents
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Config name', max_length=255)),
                ('config', models.JSONField(blank=True, help_text='Config', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Config owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('baseconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chatbot.baseconfig')),
                ('agent_type', models.IntegerField(choices=[(1, 'Open AI'), (2, 'Azure'), (3, 'Anthropic (Claude 2)'), (4, 'Amazon Bedrock'), (5, 'Fireworks (Mixtral)'), (6, 'Ollama'), (7, 'GEMINI')], default=1, help_text='Agent type')),
            ],
            bases=('chatbot.baseconfig',),
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('baseconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chatbot.baseconfig')),
                ('emb', models.IntegerField(choices=[(1, 'Open AI'), (2, 'Azure'), (4, 'Amazon Bedrock'), (5, 'Fireworks (Mixtral)'), (6, 'Ollama'), (7, 'GEMINI')], default=1, help_text='Embedding type', validators=[chatbot.models.agents.AgentType.get_embedding_validator])),
            ],
            bases=('chatbot.baseconfig',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('baseconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chatbot.baseconfig')),
                ('tool_type', models.IntegerField(choices=[(1, 'Retriever'), (2, 'Action Server'), (3, 'Arxiv'), (4, 'Connery Action'), (5, 'Dall-E Tool'), (6, 'DuckDuckGo Search'), (7, 'SEC Filings (Kay AI)'), (8, 'Press Releases (Kay AI)'), (9, 'PubMed'), (10, 'Tavily Search'), (11, 'Tavily Answer'), (12, 'You Search'), (13, 'Wikipedia')], default=1, help_text='Tool type')),
            ],
            bases=('chatbot.baseconfig',),
        ),
    ]
