# Generated by Django 4.2.13 on 2024-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='is_interrupt',
            field=models.BooleanField(blank=True, default=False, help_text='If True, Interrupt before the specific node (e.g. "action" node) when the workflow is stopped with human intervention.', verbose_name='Interrupt flag in LangGraph workflow'),
        ),
    ]
