# Generated by Django 4.2.13 on 2024-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_assistant_is_interrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, help_text='If True, the embedding process is finished.', verbose_name='Document status'),
        ),
    ]
