# Generated by Django 4.2.13 on 2024-05-08 16:40

import chatbot.models.agents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_baseconfig_config_alter_embedding_emb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Required: JSON format', null=True, verbose_name='Config'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='emb',
            field=models.IntegerField(choices=[(1, 'Open AI'), (2, 'Azure'), (4, 'Amazon Bedrock'), (5, 'Fireworks (Mixtral)'), (6, 'Ollama'), (7, 'GEMINI')], default=1, validators=[chatbot.models.agents.AgentType.get_embedding_validator], verbose_name='Embedding type'),
        ),
    ]
