# Generated by Django 4.2.13 on 2024-05-11 10:56

import chatbot.models.agents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_embedding_emb_embedding_emb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='tools', to='chatbot.tool', verbose_name='Tools used in RAG'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='emb_type',
            field=models.IntegerField(choices=[(1, 'Open AI'), (2, 'Azure'), (4, 'Amazon Bedrock'), (5, 'Fireworks (Mixtral)'), (6, 'Ollama'), (7, 'GEMINI')], default=1, validators=[chatbot.models.agents.AgentType.get_embedding_validator], verbose_name='Embedding type'),
        ),
    ]
