# Generated by Django 4.2.13 on 2024-05-11 14:56

import chatbot.models.agents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_assistant_options_alter_embedding_emb_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='emb_type',
            field=models.IntegerField(choices=[(1, 'Open AI'), (2, 'Azure'), (4, 'Amazon Bedrock'), (5, 'Fireworks (Mixtral)'), (6, 'Ollama'), (7, 'GEMINI')], default=1, validators=[chatbot.models.agents.AgentType.get_embedding_validator], verbose_name='Embedding type'),
        ),
    ]
